FROM golang:1.21-alpine

WORKDIR /app

# Install air and required packages
RUN apk add --no-cache gcc musl-dev git \
    && go install github.com/cosmtrek/air@latest

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source code
COPY . .

# Command to run air
CMD ["air"]
