version: '3.8'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SERVER_ADDRESS=:8080
  #     - MONGO_URI=mongodb://mongo:27017
  #     - MONGO_DB=vongga
  #     - REDIS_URI=redis:6379
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #     - JWT_SECRET=${JWT_SECRET}
  #     - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
  #   restart: unless-stopped
  #   depends_on:
  #     - mongo
  #     - redis

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: vongga
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: mongod --auth
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis

volumes:
  mongodb_data:
  redis_data:
