name: Deploy Vongga Backend Dev

on:
  push:
    branches:
      - develop

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: nat-prohmpiriya/vongga-backend-dev
  ENVIRONMENT: develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: develop
    
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USERNAME }}
          key: ${{ secrets.DEV_SERVER_SSH_KEY }}
          script: |
            # Pull latest image
            docker pull ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            
            # Stop and remove existing container
            docker stop vongga-backend-develop || true
            docker rm vongga-backend-develop || true
            
            # Run new container
            docker run -d \
              --name vongga-backend-develop \
              --restart always \
              --network dackbok-network \
              -p 8080:8080 \
              --env-file /home/deploy/.env.develop \
              -v /home/deploy/firebase-credentials.json:/app/firebase-credentials.json \
              ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
